### ISSUE TITLE
Running shipjs on GitHub Actions

### ISSUE THREAD

**Issue by uetchy** [algolia/shipjs#316]
**Describe the bug**
Failed to push tag to the repo while `shipjs trigger`.

https://github.com/uetchy/create-whatever/commit/2670594b2cb0b5635c00067da67d2e6bb262735e/checks?check_suite_id=257704743#step:7:36

**To Reproduce**
Run shipjs on GitHub Actions with [this workflow config](https://github.com/uetchy/create-whatever/blob/master/.github/workflows/main.yml).

```yaml
jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - uses: geertvdc/setup-hub@master
      - run: git switch master
      - run: yarn install
      - run: yarn release:trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
```

**Environment (please complete the following information):**
- Ship.js version: 0.6.0

**Additional context**
- `NPM_AUTH_TOKEN` and `GITHUB_TOKEN` has been set.
