### ISSUE TITLE
Invoke shipjs prepare from GitHub

### ISSUE THREAD

**Issue by uetchy** [algolia/shipjs#346]
`shipjs trigger` can be automated thanks to CI.
To achieve frictionless release flow within the GitHub interface, `shipjs prepare` must also be able to be invoked without manually typing the CLI command from someone's PC.

### Possible solution

1. Invoke `shipjs prepare` when someone responsible for releasing process and granted for running it (basically, admin) comments `@shipjs prepare` in an issue or PR.
2. Offer simple Web UI (like Dependabot) to provide the `Prepare Release` button.
3. (any thoughts?)

**Comment by eunjae-lee** [comment]
https://github.com/algolia/shipjs/blob/master/.circleci/config.yml#L69

You already can run shipjs prepare without interaction :) It's not yet documented well. 
What do you think? Do you see any improvements to be made there?

**Comment by uetchy** [comment]
@eunjae-lee That's awesome!
It's great if we have a way to manually initiate that process by commenting particular string on Issue/PR, in addition to scheduled release.

**Comment by eunjae-lee** [comment]
@uetchy yes! If we don't have to type `shipjs prepare` and just press a button, it'd be fantastic.

I thought about what you said, and I feel like we need to have some sort of server or whatever to monitor the comments or at least receive and handle webhooks from GitHub if there're any.
Not sure if it can be done without servers or anything. Do you have any idea?

**Comment by KnisterPeter** [comment]
@eunjae-lee Github Actions could react on comments in issues or PRs.

**Comment by uetchy** [comment]
@eunjae-lee @KnisterPeter 
I've been thinking about that. Maybe we can do that on GitHub Actions, without concerning maintaining servers:

```yaml
on:
  issue_comment:
    types: created
jobs:
  prepare_release:
    if: github.event_name == 'issue_comment' && github.event.comment.author_association == 'OWNER' && startsWith(github.event.comment.body, '@shipjs prepare')
    run-on: Ubuntu-latest
    steps:
      run: shipjs prepare
```

In that case, however, we have to resolve #316 first to ensure shipjs is compatible with GitHub Actions.
