### ISSUE TITLE
Publish package to multiple registries

### ISSUE THREAD

**Issue by jeetiss** [algolia/shipjs#600]
**Is your feature request related to a problem? Please describe.**
When I added ability to select package registry (npm or github #599), I realize that will be nice to support publishing to both of them.

But ShipJS cant do this 😔

**Describe the solution you'd like**
First solution that I figure out is add `--publishOnly` flag to trigger command.
With that flag I can easily configurate github actions, will be like: 

```yml
steps:
    # clone repo and checkout master 
  - uses: actions/checkout@master
    with:
      ref: master

    # setup node and npm with npmjs registry
  - uses: actions/setup-node@master
    with:
      registry-url: "https://registry.npmjs.org"
    
    # install shipjs and other dependencies
  - run: |
      if [ -f "yarn.lock" ]; then
        yarn install
      else
        npm install
      fi

    # trigger first release with all stuff
  - run: npm run release:trigger
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
  
    # setup node and npm with github registry
  - uses: actions/setup-node@master
    with:
      registry-url: "https://npm.pkg.github.com"
    
    # trigger second release that only publish package to registry
  - run: npm run release:trigger -- --publishOnly
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

**Describe alternatives you've considered**
I don't know any alternatives. @eunjae-lee what do you think about that? May be you offer better solution for this case.
