### ISSUE TITLE
Add example for people wants to use Release Snapshot with CI

### ISSUE THREAD

**Issue by tyankatsu0105** [algolia/shipjs#897]
**Is your feature request related to a problem? Please describe.**
The CI template that Ship.js provides is not correct for people wants to use Release Snapshot.

**Describe the solution you'd like**
Add example CI configs at "Release Snapshot" section.

**Describe alternatives you've considered**
Add example config.
For example GitHub Actions:

```diff
name: Ship js trigger
on:
+  pull_request:
+   types:
+      - closed

-   push:
-     branches:
-       - develop

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
+  if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')

    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
+        fetch-depth: 0

      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          if [ -f "yarn.lock" ]; then
            yarn install
          else
            npm install
          fi
      - run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          # SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
```

CircleCi is.... I don't know about that very much😅

**Additional context**
Or add step when use `npx shipjs setup`.
`Do you want to use "Release Snapshot"? y/N`.
If we add this step, we should refactor `addCircleCIConfig.js` and `addGitHubActions.js`.

**Comment by tyankatsu0105** [comment]
I tried to upgrade Ship.js at this repo https://github.com/tyankatsu0105/eslint-plugin/tree/v0.13.2.
Finally, it works well.

**Comment by eunjae-lee** [comment]
One of the reasons why `mergeStrategy` is removed is, user is asked about that when they try Ship.js for the first time (shipjs setup) and it might be difficult to understand if they have no experience.

Do you think [this section](https://community.algolia.com/shipjs/guide/useful-config.html#release-snapshot) is not visible enough? Or does it lack enough explanation or example?

I hope to solve this issue on the user-land (but with clear documentation). What do you think?

**Comment by tyankatsu0105** [comment]
OK. I try to explain this issue.

I created verification repo https://github.com/tyankatsu0105/verification-shipjs-897

My branch strategy is theses:

- develop => develop branch (default)
- master => keep latest release

First, this is my setup choices:

```
? What is your base branch?
  This is also called "Default branch".
  You usually merge pull-requests into this branch. develop
? Which CI configure? GitHub Actions
? Add manual prepare with issue comment?
  You can create `@shipjs prepare` comment on any issue and then github actions run `shipjs prepare` No
? Schedule your release? No
? Publish public package? Yes
```

Then this workflow was created:

```
name: Ship js trigger
on:
  push:
    branches:
      - develop
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - uses: actions/setup-node@v1
        with:
          registry-url: "https://registry.npmjs.org"
      - run: |
          if [ -f "yarn.lock" ]; then
            yarn install
          else
            npm install
          fi
      - run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
```

But this condition of `on` looks strange for me.
For example, when [this PR](https://github.com/tyankatsu0105/verification-shipjs-897/pull/2) is merged, this flow [run](https://github.com/tyankatsu0105/verification-shipjs-897/runs/789919812?check_suite_focus=true).
But this flow should run merged PR(made with `npm run release (shipjs prepare)`).
So I propose adding example changing flow.

```
on:
  pull_request:
   types:
      - closed
```

`if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')`

**Comment by tyankatsu0105** [comment]
The reason for adding `fetch-depth: 0` is a success for [Release Snapshot](https://community.algolia.com/shipjs/guide/useful-config.html#release-snapshot).
[This flow is failed](https://github.com/tyankatsu0105/verification-shipjs-897/runs/789926503?check_suite_focus=true). Because `fetch-depth: 0` is missing.

**Comment by eunjae-lee** [comment]
Hey @tyankatsu0105, Thanks for the detail.
I think it's good to add `fetch-depth: 0` to [the default config](https://github.com/algolia/shipjs/blob/main/packages/shipjs/src/step/setup/CI/addGitHubActions.js) in Ship.js, because it won't harm even if they don't do things like release snapshot.

---

About the `on` condition, that is a good point, but I think this can apply to all cases, not only to release snapshot, right?

**Comment by tyankatsu0105** [comment]
@eunjae-lee 
>I think it's good to add fetch-depth: 0 to the default config in Ship.j

OK. I will send PR for adding `fetch-depth: 0`.

>but I think this can apply to all cases, not only to release snapshot, right?

Yes. In situations where `shipjs triggers` are used, my proposed `on` condition is probably better than the current condition.
Do we change to this?:
```yml
on:
  pull_request:
   types:
      - closed
```

**Comment by eunjae-lee** [comment]
@tyankatsu0105 
yes 
```
on:
  pull_request:
   types:
      - closed
```

sounds good, but I think we should not have `startsWith(github.head_ref, 'releases/v')` because users can customize their staging branch name to something else.
