### ISSUE TITLE
failure in setting npm config in shipjs trigger

### ISSUE THREAD

**Issue by vinayakkulkarni** [algolia/shipjs#931]
**Describe the bug**
`npx shipjs trigger` doesn't work

**To Reproduce**
1. https://github.com/geospoc/v-mapbox/runs/1212948942
Check the workflow details, you'll see 

**Expected behavior**
Ideally, ship.js trigger should publish the pkg to registry, but it doesn't automatically publish to the registry.

**Screenshots**
<img width="1099" alt="Screenshot 2020-10-06 at 7 15 41 PM" src="https://user-images.githubusercontent.com/19776877/95209756-555f4680-0808-11eb-880d-1096b3a2f5f9.png">

**Environment (please complete the following information):**
 - environment: GitHub actions
 - `node -v`: 10.22.1
 - `npm -v` or `yarn -v`: 6.14.6
- Ship.js version: 0.22.0

**Additional context**
NA

**Comment by eunjae-lee** [comment]
Thanks @vinayakkulkarni for reporting the issue.

Hey @jeetiss if I remember correctly, you have dealt with an issue regarding NPM_AUTH_TOKEN before, right?
This bug is coming from my recent change. Do you have any idea what is wrong here?
If not, let me know. I will keep investigating the issue.

**Comment by KnisterPeter** [comment]
Happened for me as well. I would say, the first issue here is, that the release is marked as success but the process failed.
The release trigger should defnitly fail.

**Comment by eunjae-lee** [comment]
Oh actually this seems to be fixed in #928
Can you replace 

```
NODE_AUTH_TOKEN: \${{ secrets.NPM_AUTH_TOKEN }}
```

with

```
NPM_AUTH_TOKEN: \${{ secrets.NPM_AUTH_TOKEN }}
```

in your workflow file?

@vinayakkulkarni @KnisterPeter 

Please let me know if it fixes your issue.

**Comment by KnisterPeter** [comment]
@eunjae-lee Thanks, I'll report back when I do the next release.

**Comment by KnisterPeter** [comment]
Works fine. You close this one. :tada:

**Comment by eunjae-lee** [comment]
@KnisterPeter thanks for the confirmation 👍 

@vinayakkulkarni this will fix your issue!

**Comment by vinayakkulkarni** [comment]
Oh FYI, if anyone is facing an issue while publishing to GPR, here's a sample Shipjs trigger `.yml`:

```yml
name: Ship js trigger
on:
  pull_request:
    types:
      - closed
jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'releases/v')
    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          scope: '<@scope>'

      - name: Install dependencies 👨🏻‍💻
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release pkg to registry ⚡️
        run: npx shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
```

Apparently, NODE_AUTH_TOKEN is required for `npm publish`
Ref: https://github.com/actions/setup-node/issues/52#issuecomment-546768916
